global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'smartquitiot_backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['smartquitiot-app:8080']
        labels:
          application: 'SmartQuitIoT Backend'